language: go

go:
  - "1.10"
go_import_path: sceptred

install:
  - curl https://glide.sh/get | sh && glide install
  - npm install
  # - ./install.sh

script:
  - npm run test:js
  - go test ./server -coverprofile=./server/cover.out -covermode=atomic -tags test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
